In [1]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# Load the MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Convert labels to categorical one-hot encoding
y_train_one_hot = to_categorical(y_train, 10)
y_test_one_hot = to_categorical(y_test, 10)

# Inspect the first 10 labels in their original and one-hot encoded formats
print("Original y labels (first 10):")
print(y_train[:10])

print("\nOne-hot encoded y labels (first 10):")
print(y_train_one_hot[:10])

# Convert one-hot encoded labels back to their original integer format
y_train_reverted = np.argmax(y_train_one_hot, axis=1)

print("\nReverted y labels from one-hot encoding (first 10):")
print(y_train_reverted[:10])


Original y labels (first 10):
[5 0 4 1 9 2 1 3 1 4]

One-hot encoded y labels (first 10):
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

Reverted y labels from one-hot encoding (first 10):
[5 0 4 1 9 2 1 3 1 4]
